# Generated by Django 2.2.3 on 2019-07-09 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=255, unique=True, verbose_name='Option Name')),
                ('option_value', models.TextField(verbose_name='Option Value')),
                ('valid', models.BooleanField(default=True, verbose_name='Valid')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreateTime')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='UpdateTime')),
            ],
            options={
                'verbose_name': 'Options',
                'verbose_name_plural': 'All Options',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('position', models.CharField(default='left', max_length=255, verbose_name='Menu Position')),
                ('link_type', models.IntegerField(choices=[(0, 'Internal'), (1, 'External'), (3, 'Divide')], default=0, verbose_name='Link Type')),
                ('link', models.CharField(blank=True, help_text='support admin:index or /admin/ or http://', max_length=255, null=True, verbose_name='Link')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon')),
                ('valid', models.BooleanField(default=True, verbose_name='Valid')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('content_type', models.ForeignKey(blank=True, help_text='use for permission control.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='ContentType')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='django_admin_settings.Menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu Setting',
            },
        ),
    ]
